/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gimnasio.login.jframe;

import gimnasio.bienvenida.jframe.BienvenidaJframe;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author CUTT 5
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lblMensajeError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarLogin = new javax.swing.JButton();
        lblLoginLogo = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();
        txtIngresaUsuario = new javax.swing.JTextField();
        pswCasillaContrasenia = new javax.swing.JPasswordField();
        btnValidarLogin = new javax.swing.JButton();
        cbxMostrarContrasenia = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenesjframe/close.png"))); // NOI18N
        btnCerrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        lblLoginLogo.setFont(new java.awt.Font("BankGothic Lt BT", 1, 48)); // NOI18N
        lblLoginLogo.setText("LOGIN");
        getContentPane().add(lblLoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        lblMensajeError.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblMensajeError.setForeground(new java.awt.Color(255, 51, 51));
        lblMensajeError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenesjframe/close.png"))); // NOI18N
        lblMensajeError.setText("Es incorrecto USER  y/o  PASSWORD");
        getContentPane().add(lblMensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        txtIngresaUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtIngresaUsuario.setText("Ingresa tu Usuario");
        txtIngresaUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIngresaUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIngresaUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(txtIngresaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 351, -1));

        pswCasillaContrasenia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        pswCasillaContrasenia.setText("Ingresa tu contraseña");
        pswCasillaContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswCasillaContraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswCasillaContraseniaFocusLost(evt);
            }
        });
        getContentPane().add(pswCasillaContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 351, -1));

        btnValidarLogin.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnValidarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenesjframe/login.png"))); // NOI18N
        btnValidarLogin.setText("Login");
        btnValidarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, -1, -1));

        cbxMostrarContrasenia.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cbxMostrarContrasenia.setText("Mostrar contraseña");
        cbxMostrarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMostrarContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gimnasio/imagenesjframe/login background.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresaUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIngresaUsuarioFocusGained

        lblMensajeError.setVisible(false);
        if (txtIngresaUsuario.getText().equals("Ingresa Usuario")) {

            txtIngresaUsuario.setText("");
            txtIngresaUsuario.setForeground(new Color(0, 118, 221));

        }
    }//GEN-LAST:event_txtIngresaUsuarioFocusGained

    private void txtIngresaUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIngresaUsuarioFocusLost

        lblMensajeError.setVisible(false);
        if (txtIngresaUsuario.getText().equals("")) {

            txtIngresaUsuario.setText("Ingresa Usuario");
            txtIngresaUsuario.setForeground(new Color(0, 118, 221));
        }
    }//GEN-LAST:event_txtIngresaUsuarioFocusLost


    private void pswCasillaContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswCasillaContraseniaFocusGained

        lblMensajeError.setVisible(false);
        if (pswCasillaContrasenia.getText().equals("Ingresa Usuario")) {

            pswCasillaContrasenia.setText("");
            pswCasillaContrasenia.setForeground(new Color(0, 118, 221));

        }
    }//GEN-LAST:event_pswCasillaContraseniaFocusGained


    private void pswCasillaContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswCasillaContraseniaFocusLost

        lblMensajeError.setVisible(false);
        if (pswCasillaContrasenia.getText().equals("Ingresa Usuario")) {

            pswCasillaContrasenia.setText("");
            pswCasillaContrasenia.setForeground(new Color(0, 118, 221));

        }
    }//GEN-LAST:event_pswCasillaContraseniaFocusLost

    private void btnCerrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarLoginActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Realmente deseas salir del programa", "Selecciona", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCerrarLoginActionPerformed

    private void cbxMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMostrarContraseniaActionPerformed
        if (cbxMostrarContrasenia.isSelected()) {

            pswCasillaContrasenia.setEchoChar((char) 0);
        } else {

            pswCasillaContrasenia.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxMostrarContraseniaActionPerformed

    private void btnValidarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarLoginActionPerformed

        String usuario = txtIngresaUsuario.getText().trim();
        String password = pswCasillaContrasenia.getText().trim();

        if (txtIngresaUsuario.getText().equals("gms") && pswCasillaContrasenia.getText().equals("admin")) {
            setVisible(false);
            new BienvenidaJframe().setVisible(true);
        } else {
            lblMensajeError.setVisible(true);
        }
    }//GEN-LAST:event_btnValidarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarLogin;
    private javax.swing.JButton btnValidarLogin;
    private javax.swing.JCheckBox cbxMostrarContrasenia;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLoginLogo;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JPasswordField pswCasillaContrasenia;
    private javax.swing.JTextField txtIngresaUsuario;
    // End of variables declaration//GEN-END:variables
}
